// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTjtQbXfCwMidRTDvo1gNKdh9OMzr9QuQ',
    appId: '1:373817199106:web:5e1f16ae996e1071a6f51b',
    messagingSenderId: '373817199106',
    projectId: 'social-app-984b6',
    authDomain: 'social-app-984b6.firebaseapp.com',
    storageBucket: 'social-app-984b6.firebasestorage.app',
    measurementId: 'G-J3BVCWFP28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcceWRLQd2C06eT-cpgfpSoFDwwrhZunI',
    appId: '1:373817199106:android:424386e7ed18aa6ba6f51b',
    messagingSenderId: '373817199106',
    projectId: 'social-app-984b6',
    storageBucket: 'social-app-984b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbbTgqjVDG5pq_KabjtzctxQ0ttll0e8',
    appId: '1:373817199106:ios:a81e33dc28e453c2a6f51b',
    messagingSenderId: '373817199106',
    projectId: 'social-app-984b6',
    storageBucket: 'social-app-984b6.firebasestorage.app',
    iosBundleId: 'com.example.projekMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbbTgqjVDG5pq_KabjtzctxQ0ttll0e8',
    appId: '1:373817199106:ios:a81e33dc28e453c2a6f51b',
    messagingSenderId: '373817199106',
    projectId: 'social-app-984b6',
    storageBucket: 'social-app-984b6.firebasestorage.app',
    iosBundleId: 'com.example.projekMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTjtQbXfCwMidRTDvo1gNKdh9OMzr9QuQ',
    appId: '1:373817199106:web:131975bf945af4d7a6f51b',
    messagingSenderId: '373817199106',
    projectId: 'social-app-984b6',
    authDomain: 'social-app-984b6.firebaseapp.com',
    storageBucket: 'social-app-984b6.firebasestorage.app',
    measurementId: 'G-FL1VZSFJZT',
  );
}
